#!bash-runner

AdditionalSyncOpts=

available-options() {
  echo RemoveOlderThan
  echo AdditionalSyncOpts
}

sync() {
  rdiff-backup $AdditionalSyncOpts "$Loc1" "$Loc2"
  if [ -n "${RemoveOlderThan+a}" ]; then
    rdiff-backup $AdditionalSyncOpts --remove-older-than "$RemoveOlderThan" \
        "$Loc2"
  fi
}

versions-of() {
  path="$1"
  locNumber=$2
  if [ $locNumber = 2 ]; then
    return
  fi
  rdiff-backup --parsable-output --list-increments "$Loc2"/"$path" | \
      { grep -v missing || true; } | cut -d ' ' -f 1
}

restore() {
  path="$1"
  locNumber=$2
  timestamp=$4
  dest="$5"

  if [ $locNumber = 2 ]; then
    return
  fi

  srcFileType=$(get-repo-file-type "$path" $timestamp)
  src="$Loc2"/"$path"
  srcFileName="$(basename "$src")"

  restoringToSourceTree=0
  if [ -z "$dest" ]; then
    restoringToSourceTree=1
    dest="$Loc1"/"$path"
  fi
  destFileType=$(get-file-type "$dest" follow-links)

  fileInDest="$dest"/"$srcFileName"
  fileInDestType=$(get-file-type "$fileInDest")

  if [ $restoringToSourceTree = 0 ]; then
    if [ $destFileType = non-directory ]; then

      if [ $srcFileType = directory ]; then
        print-error "source is a directory; destination must be a directory, too"
        return 1
      fi

    elif [ $destFileType = directory ]; then
      dest="$fileInDest"

      if [ $srcFileType = directory ] && \
          [ $fileInDestType = non-directory ]; then
        print-error "destination contains non-directory ‘$srcFileName’; "\
"could not make way for source"
        return 1
      fi

      if [ $srcFileType != directory ] && [ $fileInDestType = directory ]; then
        print-error "destination contains directory ‘$srcFileName’; "\
"could not make way for source"
        return 1
      fi

    fi
  fi

  rdiff-backup --force --restore-as-of $timestamp "$src" "$dest"
}

get-repo-file-type() {
  rdiff-backup --parsable-output --list-increments \
      "$Loc2"/"$1" | sed -n -e "/^${2}/p" | cut -d ' ' -f 2
}

append-slash-if-dir() {
  while read fileName; do
    fileType=$(get-repo-file-type "$fileName" $1)
    echo -n "$fileName"

    if [ $fileType = directory ]; then
      echo -n '/'
    fi

    echo -n -e '\0'
  done
}

remove-prefix() {
  while read -d $'\0' word; do
    echo -n "${word:${#1}:${#word}}"
    echo -n -e '\0'
  done
}

list-files() {
  path="$1"
  locNumber=$2
  timestamp=$4
  recursively=$5

  if [ $locNumber = 2 ]; then
    return
  fi

  typeOfFile=$(get-repo-file-type "$path" $timestamp)
  if [ $typeOfFile != directory ]; then
    echo -n "${path##*/}"
    echo -e -n '\0'
    return
  fi

  filterDirectChildren='\,^[^/]+/[^/]+/,!p'
  prependPeriodSlash='s,^,./,'

  filter="$filterDirectChildren"
  if [ $recursively = 1 ]; then
    filter='p'
  fi

  preprocessing=''
  prefix="$path"/
  if [ "$path" = . ]; then
    prefix=./
    preprocessing="$prependPeriodSlash"
  fi

  rdiff-backup --list-at-time $timestamp "$Loc2"/"$path" | sed -n -e '1!p' |\
    sed -r -e "$preprocessing" | sed -nr -e "$filter" |\
    append-slash-if-dir $timestamp | remove-prefix "$prefix"
}
